// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CodeSandbox(lang string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.JSONScript("lang", lang).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"container\" class=\"w-full h-[600px] border\"></div><script src=\"/static/vendored/monaco-editor/min/vs/loader.js\"></script><script>\n\t\trequire.config({ paths: { vs: '/static/vendored/monaco-editor/min/vs' } });\n\n\t\trequire(['vs/editor/editor.main'], function () {\n\t\t\tconst lang = JSON.parse(document.getElementById('lang').textContent);\n\t\t\tvar editor = monaco.editor.create(document.getElementById('container'), {\n\t\t\t\tvalue: ['function x() {', '\\tconsole.log(\"Hello world!\");', '}'].join('\\n'),\n\t\t\t\tlanguage: lang\n\t\t\t});\n\n\t\t\tconst loadContent = () => {\n\t\t\t\tconst savedContent = localStorage.getItem('editor');\n\t\t\t\tif (savedContent) {\n\t\t\t\t\teditor.setValue(savedContent);\n\t\t\t\t}\n\t\t\t};\n\n\t\t\tconst saveContent = () => {\n\t\t\t\tlocalStorage.setItem('editor', editor.getValue());\n\t\t\t};\n\n\t\t\teditor.getModel().onDidChangeContent(() => {\n\t\t\t\tsaveContent();\n\t\t\t});\n\n\t\t\tloadContent();\n\n\t\t\t});\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
