// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CodeSandbox(lang string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.JSONScript("lang", lang).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"container\" class=\"w-full h-[600px] border\"></div><div class=\"flex items-center align-middle my-2 gap-2\"><button id=\"runButton\" class=\"p-2 bg-gray-700 text-white rounded hover:bg-gray-600 transition ease-in-out duration-150\" hx-post=\"/run\" hx-include=\"#editorContent\" hx-vals=\"js:{&#34;lang&#34;: JSON.parse(document.getElementById(&#34;lang&#34;).textContent)}\" hx-target=\"#output\" hx-swap=\"innerHTML\" hx-indicator=\"#spinner\">Run Code</button><div id=\"spinner\" class=\"htmx-indicator h-6 w-6 animate-spin rounded-full border-b-2 border-current\"></div></div><div id=\"output\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Output("", "").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><textarea id=\"editorContent\" name=\"code\" class=\"hidden\" hidden=\"hidden\"></textarea><script src=\"/static/vendored/monaco-editor/min/vs/loader.js\"></script><script>\n\t\trequire.config({ paths: { vs: '/static/vendored/monaco-editor/min/vs' } });\n\n\t\trequire(['vs/editor/editor.main'], function () {\n\t\t\tconst lang = JSON.parse(document.getElementById('lang').textContent);\n\t\t\tvar editor = monaco.editor.create(document.getElementById('container'), {\n\t\t\t\tvalue: \"\",\n\t\t\t\tlanguage: lang\n\t\t\t});\n\n\t\t\tconst loadContent = () => {\n\t\t\t\tconst savedContent = localStorage.getItem(lang+'editor');\n\t\t\t\tif (savedContent) {\n\t\t\t\t\teditor.setValue(savedContent);\n\t\t\t\t}\n\t\t\t};\n\n\t\t\tconst saveContent = () => {\n\t\t\t\tlocalStorage.setItem(lang+'editor', editor.getValue());\n\t\t\t\tdocument.getElementById('editorContent').value = editor.getValue();\n\t\t\t};\n\n\t\t\teditor.getModel().onDidChangeContent(() => {\n\t\t\t\tsaveContent();\n\t\t\t});\n\n\t\t\tloadContent();\n\t\t\tsaveContent();\n\n\t\t\t});\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
